packages:
  - packages/**
  - sandboxes/**
  - scripts/**
  - website

ignoredBuiltDependencies:
  - nx

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - simple-git-hooks
